<?php

$items = [
    ['id' => 1, 'name' => 'Item One', 'img' => './images/placeholder.png'],
    ['id' => 2, 'name' => 'Item Two', 'img' => './images/placeholder.png'],
    ['id' => 3, 'name' => 'Item Three', 'img' => './images/placeholder.png'],
    ['id' => 4, 'name' => 'Item Four', 'img' => './images/placeholder.png'],
    ['id' => 5, 'name' => 'Item Five', 'img' => './images/placeholder.png'],
    ['id' => 6, 'name' => 'Item Six', 'img' => './images/placeholder.png'],
    ['id' => 7, 'name' => 'Item Seven', 'img' => './images/placeholder.png'],
    ['id' => 8, 'name' => 'Item Eight', 'img' => './images/placeholder.png'],
    ['id' => 9, 'name' => 'Item Nine', 'img' => './images/placeholder.png'],
    ['id' => 10, 'name' => 'Item Ten', 'img' => './images/placeholder.png'],
    ['id' => 11, 'name' => 'Item Eleven', 'img' => './images/placeholder.png'],
    ['id' => 12, 'name' => 'Item Twelve', 'img' => './images/placeholder.png'],
    ['id' => 13, 'name' => 'Item Thirteen', 'img' => './images/placeholder.png'],
    ['id' => 14, 'name' => 'Item Fourteen', 'img' => './images/placeholder.png'],
    ['id' => 15, 'name' => 'Item Fifteen', 'img' => './images/placeholder.png'],
    ['id' => 16, 'name' => 'Item Sixteen', 'img' => './images/placeholder.png'],
    ['id' => 17, 'name' => 'Item Seventeen', 'img' => './images/placeholder.png'],
    ['id' => 18, 'name' => 'Item Eighteen', 'img' => './images/placeholder.png'],
    ['id' => 19, 'name' => 'Item Nineteen', 'img' => './images/placeholder.png'],
    ['id' => 20, 'name' => 'Item Twenty', 'img' => './images/placeholder.png'],
    ['id' => 21, 'name' => 'Item Twenty-One', 'img' => './images/placeholder.png'],
    ['id' => 22, 'name' => 'Item Twenty-Two', 'img' => './images/placeholder.png'],
    ['id' => 23, 'name' => 'Item Twenty-Three', 'img' => './images/placeholder.png'],
    ['id' => 24, 'name' => 'Item Twenty-Four', 'img' => './images/placeholder.png'],
    ['id' => 25, 'name' => 'Item Twenty-Five', 'img' => './images/placeholder.png'],
    ['id' => 26, 'name' => 'Item Twenty-Six', 'img' => './images/placeholder.png'],
    ['id' => 27, 'name' => 'Item Twenty-Seven', 'img' => './images/placeholder.png'],
    ['id' => 28, 'name' => 'Item Twenty-Eight', 'img' => './images/placeholder.png'],
    ['id' => 29, 'name' => 'Item Twenty-Nine', 'img' => './images/placeholder.png'],
    ['id' => 30, 'name' => 'Item Thirty', 'img' => './images/placeholder.png'],
    ['id' => 31, 'name' => 'Item Thirty-One', 'img' => './images/placeholder.png'],
    ['id' => 32, 'name' => 'Item Thirty-Two', 'img' => './images/placeholder.png'],
    ['id' => 33, 'name' => 'Item Thirty-Three', 'img' => './images/placeholder.png'],
    ['id' => 34, 'name' => 'Item Thirty-Four', 'img' => './images/placeholder.png'],
    ['id' => 35, 'name' => 'Item Thirty-Five', 'img' => './images/placeholder.png'],
    ['id' => 36, 'name' => 'Item Thirty-Six', 'img' => './images/placeholder.png'],
    ['id' => 37, 'name' => 'Item Thirty-Seven', 'img' => './images/placeholder.png'],
    ['id' => 38, 'name' => 'Item Thirty-Eight', 'img' => './images/placeholder.png'],
    ['id' => 39, 'name' => 'Item Thirty-Nine', 'img' => './images/placeholder.png'],
    ['id' => 40, 'name' => 'Item Forty', 'img' => './images/placeholder.png'],
];
